# input yaml for dcgan

arch: 'SNGAN'

path: '/home/alexis/Documents/AIDL/project/medical_imaging/images/ISIC-images/'
out: '/home/alexis/Documents/AIDL/project/medical_imaging/'
run: 'dummy'
seed: 42
n_gpu: 0

num_epochs: 5
learning_rate: 0.0002
beta_adam: 0.5
batch_size: 16

latent_vector: 256

image_size: 64
loader_workers: 2
number_channels: 3
gen_feature_maps: 64
dis_feature_maps: 64
